Md. Atiqur Rahman Sifat<br>ID: 0432410005101124

In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

Loading Datasets

In [2]:
movie_df_raw = pd.read_csv("D:\\UITS\\8th\\NN\\Lab\\Neural-Network\\c03\\ratings.csv")
movie_names = pd.read_csv("D:\\UITS\\8th\\NN\\Lab\\Neural-Network\\c03\\movies.csv")

In [3]:
movie_df_raw.head()

   userId  movieId  rating  timestamp
0       1        1     4.0  964982703
1       1        3     4.0  964981247
2       1        6     4.0  964982224
3       1       47     5.0  964983815
4       1       50     5.0  964982931

In [4]:
movie_names.head()

,movieId,title,genres
0,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy
1,2,Jumanji (1995),Adventure|Children|Fantasy
2,3,Grumpier Old Men (1995),Comedy|Romance
3,4,Waiting to Exhale (1995),Comedy|Drama|Romance
4,5,Father of the Bride Part II (1995),Comedy